# Generated by Django 6.0.1 on 2026-01-27 15:40

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='due_date',
            field=models.DateField(default='2026-12-31'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprint',
            name='start_date',
            field=models.DateField(db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
