# Generated by Django 6.0.1 on 2026-07-07 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0003_sprint_planned_days_alter_sprint_due_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_tasks",
                        to="boards.service",
                    ),
                ),
            ],
        ),
    ]
