# Generated by Django 6.0.1 on 2026-07-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0004_servicetask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
