# Generated by Django 6.0.1 on 2026-07-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0005_alter_service_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="description",
        ),
    ]
