# Generated by Django 6.0.1 on 2026-07-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0006_remove_service_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="title",
            field=models.CharField(max_length=40),
        ),
    ]
